stages:
    - test
    - development
    - production
# FEATURE TEST STAGE, NOT DEPLOYING TO SERVER
test:
    stage: test
    except:
        - main
        - release
    before_script:
        - echo "TEST STAGE START"
    script:
        - curl ifconfig.me && hostname -I && whoami && pwd && ls -la
    after_script:
        - echo "TEST STAGE END"
    tags:
        - development-ec2-instance
## DEVELOPMENT STAGE, CONNECTED TO PATH /usr/src/app/netplace-api AT 13.54.155.55(172.31.43.75)
deploy_to_development:
    stage: development
    only: 
      - release
    script:
    # backup
       - sudo rm -rf /usr/share/nginx/client-backup-*
       - sudo mkdir -p /usr/share/nginx/client-backup-$(date "+%Y-%m-%d")
       - sudo mkdir -p /usr/share/nginx/client && sudo touch /usr/share/nginx/client/tmp-init
       - sudo cp -r /usr/share/nginx/client/* /usr/share/nginx/client-backup-$(date "+%Y-%m-%d")
       - sudo rm /usr/share/nginx/client/tmp-init
       - sudo chown -R netplace:netplace /usr/share/nginx/client-backup-$(date "+%Y-%m-%d")
    # deploy
       - sudo mkdir -p build && sudo touch build/tmp-init
       - sudo rsync -av --progress build/* /usr/share/nginx/client
       - sudo rm build/tmp-init && sudo rm /usr/share/nginx/client/tmp-init
    tags:
        - development-ec2-instance
## PRODUCTION STAGE, CONNECTED TO PATH /usr/share/nginx/client AT 13.237.145.229(172.31.44.90)
deploy_to_production:
    stage: production
    only: 
      - main
    script:
    # backup
       - sudo rm -rf /usr/share/nginx/client-backup-*
       - sudo mkdir -p /usr/share/nginx/client-backup-$(date "+%Y-%m-%d")
       - sudo mkdir -p /usr/share/nginx/client && sudo touch /usr/share/nginx/client/tmp-init
       - sudo cp -r /usr/share/nginx/client/* /usr/share/nginx/client-backup-$(date "+%Y-%m-%d")
       - sudo rm /usr/share/nginx/client/tmp-init
       - sudo chown -R netplace:netplace /usr/share/nginx/client-backup-$(date "+%Y-%m-%d")
    # deploy
       - sudo mkdir -p build && sudo touch build/tmp-init
       - sudo rsync -av --progress build/* /usr/share/nginx/client
       - sudo rm build/tmp-init && sudo rm /usr/share/nginx/client/tmp-init
    tags:
        - production-ec2-instance